export const COMQUEST_MAGIC_SYMBOL = Symbol('COMQUEST_MAGIC_SYMBOL');
export const COMQUEST_REQUEST = Symbol('COMQUEST_REQUEST');
export const COMQUEST_SUCCESS = Symbol('COMQUEST_SUCCESS');
export const COMQUEST_FAILURE = Symbol('COMQUEST_FAILURE');
export const COMQUEST_CLEAR_DATA = Symbol('COMQUEST_CLEAR_DATA');
export const COMQUEST_CLEAR_ERRORS = Symbol('COMQUEST_CLEAR_ERRORS');
export const COMQUEST_RESET_STATE = Symbol('COMQUEST_RESET_STATE');
export const COMQUEST_ABORT_REQUESTS = Symbol('COMQUEST_ABORT_REQUESTS');
